/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package library;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.PreparedStatement;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Darius
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
        setBookDetailsToTable();
        setReaderDetailsToTable();
        setTextToCounters();
        welcomeActiveUser();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        topPanel = new javax.swing.JPanel();
        welcomeLabel = new javax.swing.JLabel();
        logoLabel = new javax.swing.JLabel();
        closeButton = new javax.swing.JButton();
        menuPanel = new javax.swing.JPanel();
        menuItem1 = new javax.swing.JPanel();
        homeLabel = new javax.swing.JLabel();
        menuLabel = new javax.swing.JLabel();
        menuItem3 = new javax.swing.JPanel();
        manageBooksLabel = new javax.swing.JLabel();
        menuItem4 = new javax.swing.JPanel();
        manageReadersLabel = new javax.swing.JLabel();
        menuItem5 = new javax.swing.JPanel();
        issueBooksLabel = new javax.swing.JLabel();
        menuItem6 = new javax.swing.JPanel();
        returnBookLabel = new javax.swing.JLabel();
        menuItem7 = new javax.swing.JPanel();
        viewRecordsLabel = new javax.swing.JLabel();
        menuItem10 = new javax.swing.JPanel();
        logOutLabel = new javax.swing.JLabel();
        menuItem11 = new javax.swing.JPanel();
        dashboardLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        bookTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        readersTable = new javax.swing.JTable();
        bookTableLabel = new javax.swing.JLabel();
        readersTableLabel = new javax.swing.JLabel();
        bookCounterPanel = new javax.swing.JPanel();
        bookCounterLabel = new javax.swing.JLabel();
        booksLabel = new javax.swing.JLabel();
        readerCounterPanel = new javax.swing.JPanel();
        readerCounterLabel = new javax.swing.JLabel();
        readersLabel = new javax.swing.JLabel();
        defaulterCounterPanel = new javax.swing.JPanel();
        defaulterCounterLabel = new javax.swing.JLabel();
        defaultersLabel = new javax.swing.JLabel();
        issuedBooksCounterPanel = new javax.swing.JPanel();
        issuesCounterLabel = new javax.swing.JLabel();
        issuesLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        backgroundPanel.setBackground(new java.awt.Color(234, 253, 248));

        topPanel.setBackground(new java.awt.Color(22, 105, 122));

        welcomeLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        welcomeLabel.setForeground(new java.awt.Color(234, 253, 248));
        welcomeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/male_user_50px.png"))); // NOI18N
        welcomeLabel.setText("Welcome,");

        logoLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        logoLabel.setForeground(new java.awt.Color(234, 253, 248));
        logoLabel.setText("Library Management System");

        closeButton.setBackground(new java.awt.Color(72, 159, 181));
        closeButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        closeButton.setForeground(new java.awt.Color(0, 0, 0));
        closeButton.setText("X");
        closeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topPanelLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(logoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(welcomeLabel)
                .addGap(63, 63, 63)
                .addComponent(closeButton)
                .addContainerGap())
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(welcomeLabel)
                    .addComponent(closeButton))
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menuPanel.setBackground(new java.awt.Color(51, 51, 51));

        menuItem1.setBackground(new java.awt.Color(72, 159, 181));
        menuItem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuItem1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuItem1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuItem1MouseExited(evt);
            }
        });

        homeLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        homeLabel.setForeground(new java.awt.Color(234, 253, 248));
        homeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_Home_26px_2.png"))); // NOI18N
        homeLabel.setText("Home Page");
        homeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout menuItem1Layout = new javax.swing.GroupLayout(menuItem1);
        menuItem1.setLayout(menuItem1Layout);
        menuItem1Layout.setHorizontalGroup(
            menuItem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuItem1Layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(homeLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menuItem1Layout.setVerticalGroup(
            menuItem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuItem1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        menuLabel.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        menuLabel.setForeground(new java.awt.Color(234, 253, 248));
        menuLabel.setText("Menu");

        menuItem3.setBackground(new java.awt.Color(102, 102, 102));
        menuItem3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuItem3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuItem3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuItem3MouseExited(evt);
            }
        });

        manageBooksLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        manageBooksLabel.setForeground(new java.awt.Color(234, 253, 248));
        manageBooksLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-open-book-30.png"))); // NOI18N
        manageBooksLabel.setText("Manage Books");
        manageBooksLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manageBooksLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                manageBooksLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                manageBooksLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout menuItem3Layout = new javax.swing.GroupLayout(menuItem3);
        menuItem3.setLayout(menuItem3Layout);
        menuItem3Layout.setHorizontalGroup(
            menuItem3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuItem3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(manageBooksLabel)
                .addGap(99, 99, 99))
        );
        menuItem3Layout.setVerticalGroup(
            menuItem3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuItem3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(manageBooksLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        menuItem4.setBackground(new java.awt.Color(102, 102, 102));
        menuItem4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuItem4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuItem4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuItem4MouseExited(evt);
            }
        });

        manageReadersLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        manageReadersLabel.setForeground(new java.awt.Color(234, 253, 248));
        manageReadersLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-read-online-30.png"))); // NOI18N
        manageReadersLabel.setText("Manage Readers");
        manageReadersLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manageReadersLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                manageReadersLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                manageReadersLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout menuItem4Layout = new javax.swing.GroupLayout(menuItem4);
        menuItem4.setLayout(menuItem4Layout);
        menuItem4Layout.setHorizontalGroup(
            menuItem4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuItem4Layout.createSequentialGroup()
                .addContainerGap(91, Short.MAX_VALUE)
                .addComponent(manageReadersLabel)
                .addGap(90, 90, 90))
        );
        menuItem4Layout.setVerticalGroup(
            menuItem4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuItem4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(manageReadersLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        menuItem5.setBackground(new java.awt.Color(102, 102, 102));
        menuItem5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuItem5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuItem5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuItem5MouseExited(evt);
            }
        });

        issueBooksLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        issueBooksLabel.setForeground(new java.awt.Color(234, 253, 248));
        issueBooksLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-give-book-32.png"))); // NOI18N
        issueBooksLabel.setText("Issue Book");
        issueBooksLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                issueBooksLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                issueBooksLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                issueBooksLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout menuItem5Layout = new javax.swing.GroupLayout(menuItem5);
        menuItem5.setLayout(menuItem5Layout);
        menuItem5Layout.setHorizontalGroup(
            menuItem5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuItem5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(issueBooksLabel)
                .addGap(114, 114, 114))
        );
        menuItem5Layout.setVerticalGroup(
            menuItem5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuItem5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(issueBooksLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        menuItem6.setBackground(new java.awt.Color(102, 102, 102));
        menuItem6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuItem6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuItem6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuItem6MouseExited(evt);
            }
        });

        returnBookLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        returnBookLabel.setForeground(new java.awt.Color(234, 253, 248));
        returnBookLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-return-book-30.png"))); // NOI18N
        returnBookLabel.setText("Return Book");
        returnBookLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                returnBookLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                returnBookLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                returnBookLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout menuItem6Layout = new javax.swing.GroupLayout(menuItem6);
        menuItem6.setLayout(menuItem6Layout);
        menuItem6Layout.setHorizontalGroup(
            menuItem6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuItem6Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(returnBookLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menuItem6Layout.setVerticalGroup(
            menuItem6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuItem6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(returnBookLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        menuItem7.setBackground(new java.awt.Color(102, 102, 102));
        menuItem7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuItem7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuItem7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuItem7MouseExited(evt);
            }
        });

        viewRecordsLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        viewRecordsLabel.setForeground(new java.awt.Color(234, 253, 248));
        viewRecordsLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-archive-list-of-parts-30.png"))); // NOI18N
        viewRecordsLabel.setText("View Records");
        viewRecordsLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewRecordsLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewRecordsLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewRecordsLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout menuItem7Layout = new javax.swing.GroupLayout(menuItem7);
        menuItem7.setLayout(menuItem7Layout);
        menuItem7Layout.setHorizontalGroup(
            menuItem7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuItem7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(viewRecordsLabel)
                .addGap(102, 102, 102))
        );
        menuItem7Layout.setVerticalGroup(
            menuItem7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuItem7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(viewRecordsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        menuItem10.setBackground(new java.awt.Color(22, 105, 122));
        menuItem10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuItem10MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuItem10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuItem10MouseExited(evt);
            }
        });

        logOutLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        logOutLabel.setForeground(new java.awt.Color(234, 253, 248));
        logOutLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_Exit_26px_2.png"))); // NOI18N
        logOutLabel.setText("Log Out");
        logOutLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logOutLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logOutLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logOutLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout menuItem10Layout = new javax.swing.GroupLayout(menuItem10);
        menuItem10.setLayout(menuItem10Layout);
        menuItem10Layout.setHorizontalGroup(
            menuItem10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuItem10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logOutLabel)
                .addGap(125, 125, 125))
        );
        menuItem10Layout.setVerticalGroup(
            menuItem10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuItem10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logOutLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        menuItem11.setBackground(new java.awt.Color(102, 102, 102));
        menuItem11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuItem11MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuItem11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuItem11MouseExited(evt);
            }
        });

        dashboardLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        dashboardLabel.setForeground(new java.awt.Color(234, 253, 248));
        dashboardLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-combo-chart-24.png"))); // NOI18N
        dashboardLabel.setText("Statistics");
        dashboardLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dashboardLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dashboardLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout menuItem11Layout = new javax.swing.GroupLayout(menuItem11);
        menuItem11.setLayout(menuItem11Layout);
        menuItem11Layout.setHorizontalGroup(
            menuItem11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuItem11Layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(dashboardLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menuItem11Layout.setVerticalGroup(
            menuItem11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuItem11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dashboardLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menuItem1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(menuItem3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(menuItem4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(menuItem5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(menuItem6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(menuItem7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(menuItem10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(menuItem11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(menuLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(menuItem1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(menuItem11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(menuItem3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(menuItem4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(menuItem5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(menuItem6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(menuItem7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(menuItem10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(477, Short.MAX_VALUE))
        );

        bookTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Book ID", "Title", "Author", "Pages", "Genre", "Publisher", "Year", "Quantity"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        bookTable.setSelectionBackground(new java.awt.Color(22, 105, 122));
        bookTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(bookTable);

        readersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "First Name", "Last Name", "Phone", "Age", "Reg. Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        readersTable.setSelectionBackground(new java.awt.Color(22, 105, 122));
        readersTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                readersTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(readersTable);

        bookTableLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bookTableLabel.setForeground(new java.awt.Color(0, 0, 0));
        bookTableLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-book2-30.png"))); // NOI18N
        bookTableLabel.setText("Books");

        readersTableLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        readersTableLabel.setForeground(new java.awt.Color(0, 0, 0));
        readersTableLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-user2-30.png"))); // NOI18N
        readersTableLabel.setText("Readers");

        bookCounterPanel.setBackground(new java.awt.Color(201, 201, 201));
        bookCounterPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(22, 105, 122)));

        bookCounterLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        bookCounterLabel.setForeground(new java.awt.Color(51, 51, 51));
        bookCounterLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_Book_Shelf_50px.png"))); // NOI18N
        bookCounterLabel.setText("0");

        booksLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        booksLabel.setForeground(new java.awt.Color(51, 51, 51));
        booksLabel.setText("Books");

        javax.swing.GroupLayout bookCounterPanelLayout = new javax.swing.GroupLayout(bookCounterPanel);
        bookCounterPanel.setLayout(bookCounterPanelLayout);
        bookCounterPanelLayout.setHorizontalGroup(
            bookCounterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookCounterPanelLayout.createSequentialGroup()
                .addGroup(bookCounterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bookCounterPanelLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(bookCounterLabel))
                    .addGroup(bookCounterPanelLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(booksLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bookCounterPanelLayout.setVerticalGroup(
            bookCounterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bookCounterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(booksLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bookCounterLabel)
                .addGap(15, 15, 15))
        );

        readerCounterPanel.setBackground(new java.awt.Color(201, 201, 201));
        readerCounterPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(72, 159, 181)));

        readerCounterLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        readerCounterLabel.setForeground(new java.awt.Color(51, 51, 51));
        readerCounterLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_People_50px.png"))); // NOI18N
        readerCounterLabel.setText("0");

        readersLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        readersLabel.setForeground(new java.awt.Color(51, 51, 51));
        readersLabel.setText("Readers");

        javax.swing.GroupLayout readerCounterPanelLayout = new javax.swing.GroupLayout(readerCounterPanel);
        readerCounterPanel.setLayout(readerCounterPanelLayout);
        readerCounterPanelLayout.setHorizontalGroup(
            readerCounterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(readerCounterPanelLayout.createSequentialGroup()
                .addGroup(readerCounterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(readerCounterPanelLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(readerCounterLabel))
                    .addGroup(readerCounterPanelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(readersLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        readerCounterPanelLayout.setVerticalGroup(
            readerCounterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, readerCounterPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(readersLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(readerCounterLabel)
                .addGap(15, 15, 15))
        );

        defaulterCounterPanel.setBackground(new java.awt.Color(201, 201, 201));
        defaulterCounterPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(72, 159, 181)));

        defaulterCounterLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        defaulterCounterLabel.setForeground(new java.awt.Color(51, 51, 51));
        defaulterCounterLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_List_of_Thumbnails_50px.png"))); // NOI18N
        defaulterCounterLabel.setText("0");

        defaultersLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        defaultersLabel.setForeground(new java.awt.Color(51, 51, 51));
        defaultersLabel.setText("Defaulters");

        javax.swing.GroupLayout defaulterCounterPanelLayout = new javax.swing.GroupLayout(defaulterCounterPanel);
        defaulterCounterPanel.setLayout(defaulterCounterPanelLayout);
        defaulterCounterPanelLayout.setHorizontalGroup(
            defaulterCounterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(defaulterCounterPanelLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(defaultersLabel)
                .addGap(17, 17, 17))
            .addGroup(defaulterCounterPanelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(defaulterCounterLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        defaulterCounterPanelLayout.setVerticalGroup(
            defaulterCounterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, defaulterCounterPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(defaultersLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(defaulterCounterLabel)
                .addGap(16, 16, 16))
        );

        issuedBooksCounterPanel.setBackground(new java.awt.Color(201, 201, 201));
        issuedBooksCounterPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(22, 105, 122)));

        issuesCounterLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        issuesCounterLabel.setForeground(new java.awt.Color(51, 51, 51));
        issuesCounterLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_Sell_50px.png"))); // NOI18N
        issuesCounterLabel.setText("0");

        issuesLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        issuesLabel.setForeground(new java.awt.Color(51, 51, 51));
        issuesLabel.setText("Issues");

        javax.swing.GroupLayout issuedBooksCounterPanelLayout = new javax.swing.GroupLayout(issuedBooksCounterPanel);
        issuedBooksCounterPanel.setLayout(issuedBooksCounterPanelLayout);
        issuedBooksCounterPanelLayout.setHorizontalGroup(
            issuedBooksCounterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(issuedBooksCounterPanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(issuedBooksCounterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(issuesCounterLabel)
                    .addComponent(issuesLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        issuedBooksCounterPanelLayout.setVerticalGroup(
            issuedBooksCounterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, issuedBooksCounterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(issuesLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(issuesCounterLabel)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout backgroundPanelLayout = new javax.swing.GroupLayout(backgroundPanel);
        backgroundPanel.setLayout(backgroundPanelLayout);
        backgroundPanelLayout.setHorizontalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(topPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bookCounterPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(readerCounterPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(issuedBooksCounterPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(defaulterCounterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundPanelLayout.createSequentialGroup()
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(37, 37, 37))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundPanelLayout.createSequentialGroup()
                            .addComponent(readersTableLabel)
                            .addGap(271, 271, 271))
                        .addGroup(backgroundPanelLayout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap()))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundPanelLayout.createSequentialGroup()
                        .addComponent(bookTableLabel)
                        .addGap(270, 270, 270))))
        );
        backgroundPanelLayout.setVerticalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addComponent(topPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(backgroundPanelLayout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(bookTableLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(readersTableLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(backgroundPanelLayout.createSequentialGroup()
                                .addComponent(bookCounterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(readerCounterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(issuedBooksCounterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(defaulterCounterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1200, 630));
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void welcomeActiveUser(){
        String text = welcomeLabel.getText();
        welcomeLabel.setText(text + " " + LogIn.activeUser + "!");
    }
    
    private void setTextToCounters(){
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/biblioteca", "root", "");
            Statement st1 = con.createStatement();
            ResultSet rs1 = st1.executeQuery("SELECT COUNT(*) FROM carti");
            if(rs1.next()){
                bookCounterLabel.setText(rs1.getString(1));
            }
            Statement st2 = con.createStatement();
            ResultSet rs2 = st2.executeQuery("SELECT COUNT(*) FROM cititori");
            if(rs2.next()){
                readerCounterLabel.setText(rs2.getString(1));
            }
            Statement st3 = con.createStatement();
            ResultSet rs3 = st3.executeQuery("SELECT COUNT(*) FROM imprumuturi");
            if(rs3.next()){
                issuesCounterLabel.setText(rs3.getString(1));
            }
            java.util.Date today = new java.util.Date();
            java.sql.Date date = new java.sql.Date(today.getTime());
            Statement st4 = con.createStatement();
            ResultSet rs4 = st4.executeQuery("SELECT COUNT(*) FROM imprumuturi WHERE data_expirare < '" + date + "' AND status = 'Pending'");
            if(rs4.next()){
                defaulterCounterLabel.setText(rs4.getString(1));
            }
        } catch (Exception e) {
            e.getStackTrace();
        }
    }
    
    private void manageBooksLabelMouseClicked(java.awt.event.MouseEvent evt) {                                              
        ManageBooks manageBooks = new ManageBooks();
        manageBooks.setVisible(true);
        this.dispose();
    }                                             

    private void menuItem10MouseClicked(java.awt.event.MouseEvent evt) {                                        
        // TODO add your handling code here:
        LogIn login = new LogIn();
        login.setVisible(true);
        this.dispose();
    }                                       

    private void menuItem4MouseClicked(java.awt.event.MouseEvent evt) {                                       
        ManageReaders manageReaders = new ManageReaders();
        manageReaders.setVisible(true);
        this.dispose();
    }                                      

    private void closeButtonMouseClicked(java.awt.event.MouseEvent evt) {                                         
        System.exit(0);
    }                                        

    private void menuItem3MouseEntered(java.awt.event.MouseEvent evt) {                                       
        menuItem3.setBackground(new Color(72,159,181));
    }                                      

    private void menuItem3MouseExited(java.awt.event.MouseEvent evt) {                                      
        menuItem3.setBackground(new Color(102,102,102));
    }                                     

    private void menuItem3MouseClicked(java.awt.event.MouseEvent evt) {                                       
        ManageBooks manageBooks = new ManageBooks();
        manageBooks.setVisible(true);
        this.dispose();
    }                                      

    private void manageBooksLabelMouseEntered(java.awt.event.MouseEvent evt) {                                              
        menuItem3.setBackground(new Color(72,159,181));
    }                                             

    private void manageBooksLabelMouseExited(java.awt.event.MouseEvent evt) {                                             
        menuItem3.setBackground(new Color(102,102,102));
    }                                            

    private void menuItem1MouseClicked(java.awt.event.MouseEvent evt) {                                       
        HomePage home = new HomePage();
        home.setVisible(true);
        this.dispose();
    }                                      

    private void menuItem1MouseEntered(java.awt.event.MouseEvent evt) {                                       
        menuItem1.setBackground(new Color(22,105,122));
    }                                      

    private void menuItem1MouseExited(java.awt.event.MouseEvent evt) {                                      
        menuItem1.setBackground(new Color(72,159,181));
    }                                     

    private void homeLabelMouseClicked(java.awt.event.MouseEvent evt) {                                       
        HomePage home = new HomePage();
        home.setVisible(true);
        dispose();
    }                                      

    private void homeLabelMouseEntered(java.awt.event.MouseEvent evt) {                                       
        menuItem1.setBackground(new Color(22,105,122));
    }                                      

    private void homeLabelMouseExited(java.awt.event.MouseEvent evt) {                                      
        menuItem1.setBackground(new Color(72,159,181));
    }                                     

    private void manageReadersLabelMouseClicked(java.awt.event.MouseEvent evt) {                                                
        ManageReaders manageReaders = new ManageReaders();
        manageReaders.setVisible(true);
        this.dispose();
    }                                               

    private void manageReadersLabelMouseEntered(java.awt.event.MouseEvent evt) {                                                
        menuItem4.setBackground(new Color(72,159,181));
    }                                               

    private void manageReadersLabelMouseExited(java.awt.event.MouseEvent evt) {                                               
        menuItem4.setBackground(new Color(102,102,102));
    }                                              

    private void menuItem4MouseEntered(java.awt.event.MouseEvent evt) {                                       
        menuItem4.setBackground(new Color(72,159,181));
    }                                      

    private void menuItem4MouseExited(java.awt.event.MouseEvent evt) {                                      
        menuItem4.setBackground(new Color(102,102,102));
    }                                     

    private void menuItem5MouseClicked(java.awt.event.MouseEvent evt) {                                       
        IssueBook issueBook = new IssueBook();
        issueBook.setVisible(true);
        this.dispose();
    }                                      

    private void menuItem5MouseEntered(java.awt.event.MouseEvent evt) {                                       
        menuItem5.setBackground(new Color(72,159,181));
    }                                      

    private void menuItem5MouseExited(java.awt.event.MouseEvent evt) {                                      
        menuItem5.setBackground(new Color(102,102,102));
    }                                     

    private void issueBooksLabelMouseClicked(java.awt.event.MouseEvent evt) {                                             
        IssueBook issueBook = new IssueBook();
        issueBook.setVisible(true);
        this.dispose();
    }                                            

    private void issueBooksLabelMouseEntered(java.awt.event.MouseEvent evt) {                                             
        menuItem5.setBackground(new Color(72,159,181));
    }                                            

    private void issueBooksLabelMouseExited(java.awt.event.MouseEvent evt) {                                            
        menuItem5.setBackground(new Color(102,102,102));
    }                                           

    private void menuItem6MouseClicked(java.awt.event.MouseEvent evt) {                                       
        ReturnBook returnBook = new ReturnBook();
        returnBook.setVisible(true);
        this.dispose();
    }                                      

    private void menuItem6MouseEntered(java.awt.event.MouseEvent evt) {                                       
        menuItem6.setBackground(new Color(72,159,181));
    }                                      

    private void menuItem6MouseExited(java.awt.event.MouseEvent evt) {                                      
        menuItem6.setBackground(new Color(102,102,102));
    }                                     

    private void returnBookLabelMouseClicked(java.awt.event.MouseEvent evt) {                                             
        ReturnBook returnBook = new ReturnBook();
        returnBook.setVisible(true);
        this.dispose();
    }                                            

    private void returnBookLabelMouseEntered(java.awt.event.MouseEvent evt) {                                             
        menuItem6.setBackground(new Color(72,159,181));
    }                                            

    private void returnBookLabelMouseExited(java.awt.event.MouseEvent evt) {                                            
        menuItem6.setBackground(new Color(102,102,102));
    }                                           

    private void menuItem7MouseClicked(java.awt.event.MouseEvent evt) {                                       
        ViewRecords viewRecords = new ViewRecords();
        viewRecords.setVisible(true);
        this.dispose();
    }                                      

    private void menuItem7MouseEntered(java.awt.event.MouseEvent evt) {                                       
        menuItem7.setBackground(new Color(72,159,181));
    }                                      

    private void menuItem7MouseExited(java.awt.event.MouseEvent evt) {                                      
        menuItem7.setBackground(new Color(102,102,102));
    }                                     

    private void viewRecordsLabelMouseClicked(java.awt.event.MouseEvent evt) {                                              
        ViewRecords viewRecords = new ViewRecords();
        viewRecords.setVisible(true);
        this.dispose();
    }                                             

    private void viewRecordsLabelMouseEntered(java.awt.event.MouseEvent evt) {                                              
        menuItem7.setBackground(new Color(72,159,181));
    }                                             

    private void viewRecordsLabelMouseExited(java.awt.event.MouseEvent evt) {                                             
        menuItem7.setBackground(new Color(102,102,102));
    }                                            

    private void menuItem10MouseEntered(java.awt.event.MouseEvent evt) {                                        
        menuItem10.setBackground(new Color(72,159,181));
    }                                       

    private void menuItem10MouseExited(java.awt.event.MouseEvent evt) {                                       
        menuItem10.setBackground(new Color(22,105,122));
    }                                      

    private void logOutLabelMouseClicked(java.awt.event.MouseEvent evt) {                                         
        LogIn login = new LogIn();
        login.setVisible(true);
        this.dispose();
    }                                        

    private void logOutLabelMouseEntered(java.awt.event.MouseEvent evt) {                                         
        menuItem10.setBackground(new Color(72,159,181));
    }                                        

    private void logOutLabelMouseExited(java.awt.event.MouseEvent evt) {                                        
        menuItem10.setBackground(new Color(22,105,122));
    }                                       

    private void bookTableMouseClicked(java.awt.event.MouseEvent evt) {                                       
        //TODO
    }                                      
    
    public void setBookDetailsToTable(){
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/biblioteca", "root", "");
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT id_carte 'ID', titlu 'Title', autor 'Author', nr_pagini 'Pages', gen 'Genre', "
                    + "editura 'Publisher', an_aparitie 'Release Year', cantitate 'Quantity' FROM carti");
            bookTable.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            // TODO: handle exception
            e.getStackTrace();
        }
    }
    
    public void setReaderDetailsToTable(){
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/biblioteca", "root", "");
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT id_cititor 'ID', prenume 'First Name', nume 'Last Name', telefon 'Phone', varsta 'Age', "
                    + "data_inregistrarii 'Reg. Date' FROM cititori");
            readersTable.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            // TODO: handle exception
            e.getStackTrace();
        }
    }
    
    private void readersTableMouseClicked(java.awt.event.MouseEvent evt) {                                          
        //TODO
    }                                         

    private void dashboardLabelMouseClicked(java.awt.event.MouseEvent evt) {                                            
        Statistics statistics = new Statistics();
        statistics.setVisible(true);
        this.dispose();
    }                                           

    private void dashboardLabelMouseEntered(java.awt.event.MouseEvent evt) {                                            
        menuItem11.setBackground(new Color(72,159,181));
    }                                           

    private void dashboardLabelMouseExited(java.awt.event.MouseEvent evt) {                                           
        menuItem11.setBackground(new Color(102,102,102));
    }                                          

    private void menuItem11MouseClicked(java.awt.event.MouseEvent evt) {                                        
        Statistics statistics = new Statistics();
        statistics.setVisible(true);
        this.dispose();
    }                                       

    private void menuItem11MouseEntered(java.awt.event.MouseEvent evt) {                                        
        menuItem11.setBackground(new Color(72,159,181));
    }                                       

    private void menuItem11MouseExited(java.awt.event.MouseEvent evt) {                                       
        menuItem11.setBackground(new Color(102,102,102));
    }                                      

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JLabel bookCounterLabel;
    private javax.swing.JPanel bookCounterPanel;
    private javax.swing.JTable bookTable;
    private javax.swing.JLabel bookTableLabel;
    private javax.swing.JLabel booksLabel;
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel dashboardLabel;
    private javax.swing.JLabel defaulterCounterLabel;
    private javax.swing.JPanel defaulterCounterPanel;
    private javax.swing.JLabel defaultersLabel;
    private javax.swing.JLabel homeLabel;
    private javax.swing.JLabel issueBooksLabel;
    private javax.swing.JPanel issuedBooksCounterPanel;
    private javax.swing.JLabel issuesCounterLabel;
    private javax.swing.JLabel issuesLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel logOutLabel;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JLabel manageBooksLabel;
    private javax.swing.JLabel manageReadersLabel;
    private javax.swing.JPanel menuItem1;
    private javax.swing.JPanel menuItem10;
    private javax.swing.JPanel menuItem11;
    private javax.swing.JPanel menuItem3;
    private javax.swing.JPanel menuItem4;
    private javax.swing.JPanel menuItem5;
    private javax.swing.JPanel menuItem6;
    private javax.swing.JPanel menuItem7;
    private javax.swing.JLabel menuLabel;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JLabel readerCounterLabel;
    private javax.swing.JPanel readerCounterPanel;
    private javax.swing.JLabel readersLabel;
    private javax.swing.JTable readersTable;
    private javax.swing.JLabel readersTableLabel;
    private javax.swing.JLabel returnBookLabel;
    private javax.swing.JPanel topPanel;
    private javax.swing.JLabel viewRecordsLabel;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration                   
}
