/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package library;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Date;

import javax.swing.JOptionPane;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Darius
 */
public class ManageReaders extends javax.swing.JFrame {
    DefaultTableModel model;

    /**
     * Creates new form ManageBooks
     */
    public ManageReaders() {
        initComponents();
        setReaderDetailsToTable();
    }

    // Method to set details of the readers into the table
    public void setReaderDetailsToTable(){
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/biblioteca", "root", "");
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT id_cititor 'ID', prenume 'First Name', nume 'Last Name', email 'E-Mail', telefon 'Phone', "
                    + "varsta 'Age', data_inregistrarii 'Reg. Date' FROM cititori");
            readersTable.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            // TODO: handle exception
            e.getStackTrace();
        }
    }
    // method to add books
    public boolean addReader(){
        boolean isAdded = false;
        java.util.Date registrationDate = registrationDateChooser.getDate();
        java.sql.Date inputRegistrationDate = new java.sql.Date(registrationDate.getTime());
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/biblioteca", "root", "");
            PreparedStatement pst = con.prepareStatement("INSERT INTO cititori VALUES (?,?,?,?,?,?,?)");
            pst.setInt(1, Integer.parseInt(idField.getText()));
            pst.setString(2, firstNameField.getText());
            pst.setString(3, lastNameField.getText());
            pst.setString(4, emailField.getText());
            pst.setString(5, phoneField.getText());
            pst.setInt(6, Integer.parseInt(ageField.getText()));
            pst.setDate(7, inputRegistrationDate);

            int rowCount = pst.executeUpdate();
            if(rowCount > 0)
                isAdded = true;
            else
                isAdded = false;

        } catch (Exception e) {
            // TODO: handle exception
            e.printStackTrace();
        }
        return isAdded;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        formPanel = new javax.swing.JPanel();
        backHome = new javax.swing.JButton();
        idLabel = new javax.swing.JLabel();
        firstNameField = new javax.swing.JTextField();
        firstNameLabel = new javax.swing.JLabel();
        lastNameLabel = new javax.swing.JLabel();
        lastNameField = new javax.swing.JTextField();
        phoneNumberLabel = new javax.swing.JLabel();
        ageLabel = new javax.swing.JLabel();
        ageField = new javax.swing.JTextField();
        registrationDateLabel = new javax.swing.JLabel();
        addReaderButton = new javax.swing.JButton();
        updateReaderButton = new javax.swing.JButton();
        deleteReaderButton = new javax.swing.JButton();
        idField = new javax.swing.JTextField();
        phoneField = new javax.swing.JTextField();
        registrationDateChooser = new com.toedter.calendar.JDateChooser();
        emailField = new javax.swing.JTextField();
        lastNameLabel1 = new javax.swing.JLabel();
        tablePanel = new javax.swing.JPanel();
        closeButton = new javax.swing.JButton();
        manageReadersLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        readersTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));

        formPanel.setBackground(new java.awt.Color(22, 105, 122));

        backHome.setBackground(new java.awt.Color(72, 159, 181));
        backHome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        backHome.setForeground(new java.awt.Color(0, 0, 0));
        backHome.setText("Back Home");
        backHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backHomeMouseClicked(evt);
            }
        });

        idLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        idLabel.setForeground(new java.awt.Color(234, 253, 248));
        idLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-user-30.png"))); // NOI18N
        idLabel.setText("Reader's ID");

        firstNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        firstNameLabel.setForeground(new java.awt.Color(234, 253, 248));
        firstNameLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-badge-30.png"))); // NOI18N
        firstNameLabel.setText("Reader's First Name");

        lastNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lastNameLabel.setForeground(new java.awt.Color(234, 253, 248));
        lastNameLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-badge-30.png"))); // NOI18N
        lastNameLabel.setText("Reader's Last Name");

        phoneNumberLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        phoneNumberLabel.setForeground(new java.awt.Color(234, 253, 248));
        phoneNumberLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-phone-30.png"))); // NOI18N
        phoneNumberLabel.setText("Reader's Phone Number");

        ageLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        ageLabel.setForeground(new java.awt.Color(234, 253, 248));
        ageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-age-timeline-30.png"))); // NOI18N
        ageLabel.setText("Reader's Age");

        registrationDateLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        registrationDateLabel.setForeground(new java.awt.Color(234, 253, 248));
        registrationDateLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-calendar-30.png"))); // NOI18N
        registrationDateLabel.setText("Registration Date");

        addReaderButton.setBackground(new java.awt.Color(72, 159, 181));
        addReaderButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addReaderButton.setForeground(new java.awt.Color(0, 0, 0));
        addReaderButton.setText("Add Reader");
        addReaderButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addReaderButtonMouseClicked(evt);
            }
        });

        updateReaderButton.setBackground(new java.awt.Color(72, 159, 181));
        updateReaderButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        updateReaderButton.setForeground(new java.awt.Color(0, 0, 0));
        updateReaderButton.setText("Update Reader");
        updateReaderButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateReaderButtonMouseClicked(evt);
            }
        });

        deleteReaderButton.setBackground(new java.awt.Color(72, 159, 181));
        deleteReaderButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        deleteReaderButton.setForeground(new java.awt.Color(0, 0, 0));
        deleteReaderButton.setText("Delete Reader");
        deleteReaderButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteReaderButtonMouseClicked(evt);
            }
        });

        lastNameLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lastNameLabel1.setForeground(new java.awt.Color(234, 253, 248));
        lastNameLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-secured-letter2-30.png"))); // NOI18N
        lastNameLabel1.setText("Reader's E-Mail");

        javax.swing.GroupLayout formPanelLayout = new javax.swing.GroupLayout(formPanel);
        formPanel.setLayout(formPanelLayout);
        formPanelLayout.setHorizontalGroup(
            formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formPanelLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(addReaderButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                        .addComponent(deleteReaderButton))
                    .addGroup(formPanelLayout.createSequentialGroup()
                        .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(backHome)
                            .addGroup(formPanelLayout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(firstNameLabel)
                                    .addComponent(lastNameLabel)
                                    .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(phoneNumberLabel)
                                            .addComponent(registrationDateLabel)
                                            .addComponent(ageLabel)
                                            .addGroup(formPanelLayout.createSequentialGroup()
                                                .addGap(50, 50, 50)
                                                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(ageField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(phoneField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(registrationDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(formPanelLayout.createSequentialGroup()
                                            .addGap(50, 50, 50)
                                            .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(lastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(firstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lastNameLabel1)
                                            .addGroup(formPanelLayout.createSequentialGroup()
                                                .addGap(50, 50, 50)
                                                .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(idLabel))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(26, 26, 26))
            .addGroup(formPanelLayout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(updateReaderButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        formPanelLayout.setVerticalGroup(
            formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backHome)
                .addGap(38, 38, 38)
                .addComponent(idLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(firstNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(firstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lastNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(lastNameLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(phoneNumberLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(phoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ageLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ageField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(registrationDateLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(registrationDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addReaderButton)
                    .addComponent(deleteReaderButton))
                .addGap(18, 18, 18)
                .addComponent(updateReaderButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tablePanel.setBackground(new java.awt.Color(234, 253, 248));

        closeButton.setBackground(new java.awt.Color(72, 159, 181));
        closeButton.setForeground(new java.awt.Color(0, 0, 0));
        closeButton.setText("X");
        closeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeButtonMouseClicked(evt);
            }
        });

        manageReadersLabel.setBackground(new java.awt.Color(255, 0, 51));
        manageReadersLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        manageReadersLabel.setForeground(new java.awt.Color(0, 0, 0));
        manageReadersLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-people-50.png"))); // NOI18N
        manageReadersLabel.setText("Manage Readers");

        javax.swing.GroupLayout tablePanelLayout = new javax.swing.GroupLayout(tablePanel);
        tablePanel.setLayout(tablePanelLayout);
        tablePanelLayout.setHorizontalGroup(
            tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tablePanelLayout.createSequentialGroup()
                .addContainerGap(187, Short.MAX_VALUE)
                .addGroup(tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tablePanelLayout.createSequentialGroup()
                        .addComponent(closeButton)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tablePanelLayout.createSequentialGroup()
                        .addComponent(manageReadersLabel)
                        .addGap(182, 182, 182))))
        );
        tablePanelLayout.setVerticalGroup(
            tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tablePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(closeButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(manageReadersLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        readersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "First Name", "Last Name", "E-Mail", "Phone", "Age", "Reg. Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        readersTable.setSelectionBackground(new java.awt.Color(22, 105, 122));
        readersTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                readersTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(readersTable);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(formPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(formPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(tablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void backHomeMouseClicked(java.awt.event.MouseEvent evt) {                                      
        // TODO add your handling code here:
        HomePage home = new HomePage();
        home.setVisible(true);
        dispose();
    }                                     

    private void readersTableMouseClicked(java.awt.event.MouseEvent evt) {                                          
        int rowNumber = readersTable.getSelectedRow();
        TableModel model = readersTable.getModel();
        idField.setText(model.getValueAt(rowNumber, 0).toString());
        firstNameField.setText(model.getValueAt(rowNumber, 1).toString());
        lastNameField.setText(model.getValueAt(rowNumber, 2).toString());
        emailField.setText(model.getValueAt(rowNumber, 3).toString());
        phoneField.setText(model.getValueAt(rowNumber, 4).toString());
        ageField.setText(model.getValueAt(rowNumber, 5).toString());
        registrationDateChooser.setDate((java.sql.Date)model.getValueAt(rowNumber, 6));
    }                                         

    private void addReaderButtonMouseClicked(java.awt.event.MouseEvent evt) {                                             
        if(addReader() == true){
            JOptionPane.showMessageDialog(this, "Reader Added Successfully!");
            setReaderDetailsToTable();
        }
        else
        JOptionPane.showMessageDialog(this, "Reader was not added!");   
    }                                            

    private void closeButtonMouseClicked(java.awt.event.MouseEvent evt) {                                         
        System.exit(0);
    }                                        

    private void updateReaderButtonMouseClicked(java.awt.event.MouseEvent evt) {                                                
        java.util.Date registrationDate = registrationDateChooser.getDate();
        java.sql.Date inputRegistrationDate = new java.sql.Date(registrationDate.getTime());
        if(idField.getText().isEmpty() || firstNameField.getText().isEmpty() || lastNameField.getText().isEmpty() || emailField.getText().isEmpty() || phoneField.getText().isEmpty() || ageField.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Reader information was not selected!");
        }
        else{
            try{
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/biblioteca", "root", "");
                String updateQuery = "UPDATE cititori SET prenume = '"+ firstNameField.getText() + "',  nume = '"+ lastNameField.getText() + "', email = '"+emailField.getText()+"', "
                        + "telefon = '"+ phoneField.getText() + "', varsta = '" + ageField.getText() + "', data_inregistrarii = '"+ inputRegistrationDate + "' WHERE id_cititor = " + idField.getText() + ";";
                Statement add = con.createStatement();
                add.executeUpdate(updateQuery);
                JOptionPane.showMessageDialog(this, "Reader updated successfully!");
            } catch(Exception e){
                e.printStackTrace();
            }
            setReaderDetailsToTable();
        }
    }                                               

    private void deleteReaderButtonMouseClicked(java.awt.event.MouseEvent evt) {                                                
        if(idField.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Select a Reader to delete!");
        }
        else{
            try{
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/biblioteca", "root", "");
                String idToDelete = idField.getText();
                String query = "DELETE FROM cititori WHERE id_cititor = " + idToDelete;
                Statement add = con.createStatement();
                add.executeUpdate(query);
                setReaderDetailsToTable();
                JOptionPane.showMessageDialog(this, "Reader deleted successfully!");
            } catch(Exception e){
                e.printStackTrace();
            }
        }
    }                                               

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageReaders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageReaders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageReaders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageReaders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageReaders().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton addReaderButton;
    private javax.swing.JTextField ageField;
    private javax.swing.JLabel ageLabel;
    private javax.swing.JButton backHome;
    private javax.swing.JButton closeButton;
    private javax.swing.JButton deleteReaderButton;
    private javax.swing.JTextField emailField;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JPanel formPanel;
    private javax.swing.JTextField idField;
    private javax.swing.JLabel idLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JLabel lastNameLabel1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel manageReadersLabel;
    private javax.swing.JTextField phoneField;
    private javax.swing.JLabel phoneNumberLabel;
    private javax.swing.JTable readersTable;
    private com.toedter.calendar.JDateChooser registrationDateChooser;
    private javax.swing.JLabel registrationDateLabel;
    private javax.swing.JPanel tablePanel;
    private javax.swing.JButton updateReaderButton;
    // End of variables declaration                   
}
