/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package library;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Darius
 */
public class ReturnBook extends javax.swing.JFrame {

    /**
     * Creates new form ReturnBook
     */
    public ReturnBook() {
        initComponents();
        setRecordDetailsToTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bookDetailsPanel = new javax.swing.JPanel();
        backHome = new javax.swing.JButton();
        bookDetailsLabel = new javax.swing.JLabel();
        issueIdLabel = new javax.swing.JLabel();
        bookTitleLabel = new javax.swing.JLabel();
        firstNameLabel = new javax.swing.JLabel();
        lastNameLabel = new javax.swing.JLabel();
        issueDateLabel = new javax.swing.JLabel();
        dueDateLabel = new javax.swing.JLabel();
        issueIdEmptyLabel = new javax.swing.JLabel();
        bookTitleEmptyLabel = new javax.swing.JLabel();
        firstNameEmptyLabel = new javax.swing.JLabel();
        lastNameEmptyLabel = new javax.swing.JLabel();
        issueDateEmptyLabel = new javax.swing.JLabel();
        dueDateEmptyLabel = new javax.swing.JLabel();
        issueErrorLabel = new javax.swing.JLabel();
        readerDetailPanel = new javax.swing.JPanel();
        findIssueButton = new javax.swing.JButton();
        returnReaderIdField = new javax.swing.JTextField();
        issueReaderIdLabel = new javax.swing.JLabel();
        returnBookIdField = new javax.swing.JTextField();
        issueBookIdLabel = new javax.swing.JLabel();
        returnBookLabel = new javax.swing.JLabel();
        returnBookButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        recordsTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(234, 253, 248));

        bookDetailsPanel.setBackground(new java.awt.Color(22, 105, 122));

        backHome.setBackground(new java.awt.Color(72, 159, 181));
        backHome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        backHome.setForeground(new java.awt.Color(0, 0, 0));
        backHome.setText("Back Home");
        backHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backHomeMouseClicked(evt);
            }
        });

        bookDetailsLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        bookDetailsLabel.setForeground(new java.awt.Color(234, 253, 248));
        bookDetailsLabel.setText("Issue Details");

        issueIdLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        issueIdLabel.setForeground(new java.awt.Color(234, 253, 248));
        issueIdLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-give-book-32.png"))); // NOI18N
        issueIdLabel.setText("Issue ID:");

        bookTitleLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        bookTitleLabel.setForeground(new java.awt.Color(234, 253, 248));
        bookTitleLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-title-32.png"))); // NOI18N
        bookTitleLabel.setText("Title:");

        firstNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        firstNameLabel.setForeground(new java.awt.Color(234, 253, 248));
        firstNameLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-badge-30.png"))); // NOI18N
        firstNameLabel.setText("Reader's First Name:");

        lastNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lastNameLabel.setForeground(new java.awt.Color(234, 253, 248));
        lastNameLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-badge-30.png"))); // NOI18N
        lastNameLabel.setText("Reader's Last Name:");

        issueDateLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        issueDateLabel.setForeground(new java.awt.Color(234, 253, 248));
        issueDateLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-calendar-30.png"))); // NOI18N
        issueDateLabel.setText("Issue Date:");

        dueDateLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        dueDateLabel.setForeground(new java.awt.Color(234, 253, 248));
        dueDateLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-calendar-30.png"))); // NOI18N
        dueDateLabel.setText("Due Date:");

        issueIdEmptyLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        issueIdEmptyLabel.setForeground(new java.awt.Color(234, 253, 248));
        issueIdEmptyLabel.setText("x");

        bookTitleEmptyLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        bookTitleEmptyLabel.setForeground(new java.awt.Color(234, 253, 248));
        bookTitleEmptyLabel.setText("x");

        firstNameEmptyLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        firstNameEmptyLabel.setForeground(new java.awt.Color(234, 253, 248));
        firstNameEmptyLabel.setText("x");

        lastNameEmptyLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lastNameEmptyLabel.setForeground(new java.awt.Color(234, 253, 248));
        lastNameEmptyLabel.setText("x");

        issueDateEmptyLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        issueDateEmptyLabel.setForeground(new java.awt.Color(234, 253, 248));
        issueDateEmptyLabel.setText("x");

        dueDateEmptyLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        dueDateEmptyLabel.setForeground(new java.awt.Color(234, 253, 248));
        dueDateEmptyLabel.setText("x");

        issueErrorLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        issueErrorLabel.setForeground(new java.awt.Color(241, 211, 2));

        javax.swing.GroupLayout bookDetailsPanelLayout = new javax.swing.GroupLayout(bookDetailsPanel);
        bookDetailsPanel.setLayout(bookDetailsPanelLayout);
        bookDetailsPanelLayout.setHorizontalGroup(
            bookDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bookDetailsPanelLayout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addComponent(bookDetailsLabel)
                .addGap(77, 77, 77))
            .addGroup(bookDetailsPanelLayout.createSequentialGroup()
                .addGroup(bookDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bookDetailsPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backHome))
                    .addGroup(bookDetailsPanelLayout.createSequentialGroup()
                        .addGroup(bookDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bookDetailsPanelLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(bookDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(bookDetailsPanelLayout.createSequentialGroup()
                                        .addComponent(issueIdLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(issueIdEmptyLabel))
                                    .addComponent(lastNameLabel)
                                    .addGroup(bookDetailsPanelLayout.createSequentialGroup()
                                        .addComponent(bookTitleLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(bookTitleEmptyLabel))
                                    .addComponent(firstNameLabel)
                                    .addComponent(issueDateLabel)
                                    .addComponent(dueDateLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bookDetailsPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(issueErrorLabel)
                                .addGap(104, 104, 104)))
                        .addGroup(bookDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(firstNameEmptyLabel)
                            .addComponent(lastNameEmptyLabel)
                            .addComponent(issueDateEmptyLabel)
                            .addComponent(dueDateEmptyLabel))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bookDetailsPanelLayout.setVerticalGroup(
            bookDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookDetailsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bookDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(bookDetailsPanelLayout.createSequentialGroup()
                        .addComponent(firstNameEmptyLabel)
                        .addGap(18, 18, 18)
                        .addComponent(lastNameEmptyLabel)
                        .addGap(18, 18, 18)
                        .addComponent(issueDateEmptyLabel)
                        .addGap(18, 18, 18)
                        .addComponent(dueDateEmptyLabel))
                    .addGroup(bookDetailsPanelLayout.createSequentialGroup()
                        .addComponent(backHome)
                        .addGap(36, 36, 36)
                        .addComponent(bookDetailsLabel)
                        .addGap(69, 69, 69)
                        .addGroup(bookDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(issueIdLabel)
                            .addComponent(issueIdEmptyLabel))
                        .addGap(18, 18, 18)
                        .addGroup(bookDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bookTitleLabel)
                            .addComponent(bookTitleEmptyLabel))
                        .addGap(18, 18, 18)
                        .addComponent(firstNameLabel)
                        .addGap(18, 18, 18)
                        .addComponent(lastNameLabel)
                        .addGap(18, 18, 18)
                        .addComponent(issueDateLabel)
                        .addGap(18, 18, 18)
                        .addComponent(dueDateLabel)))
                .addGap(37, 37, 37)
                .addComponent(issueErrorLabel)
                .addContainerGap(119, Short.MAX_VALUE))
        );

        readerDetailPanel.setBackground(new java.awt.Color(72, 159, 181));

        findIssueButton.setBackground(new java.awt.Color(22, 105, 122));
        findIssueButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        findIssueButton.setForeground(new java.awt.Color(234, 253, 248));
        findIssueButton.setText("Find Issue");
        findIssueButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                findIssueButtonMouseClicked(evt);
            }
        });
        findIssueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findIssueButtonActionPerformed(evt);
            }
        });

        returnReaderIdField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                returnReaderIdFieldFocusLost(evt);
            }
        });
        returnReaderIdField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnReaderIdFieldActionPerformed(evt);
            }
        });

        issueReaderIdLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        issueReaderIdLabel.setForeground(new java.awt.Color(234, 253, 248));
        issueReaderIdLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-user-30.png"))); // NOI18N
        issueReaderIdLabel.setText("Reader ID:");

        returnBookIdField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                returnBookIdFieldFocusLost(evt);
            }
        });

        issueBookIdLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        issueBookIdLabel.setForeground(new java.awt.Color(234, 253, 248));
        issueBookIdLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-book-30.png"))); // NOI18N
        issueBookIdLabel.setText("Book ID:");

        returnBookLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        returnBookLabel.setForeground(new java.awt.Color(234, 253, 248));
        returnBookLabel.setText("Return Book");

        returnBookButton.setBackground(new java.awt.Color(22, 105, 122));
        returnBookButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        returnBookButton.setForeground(new java.awt.Color(234, 253, 248));
        returnBookButton.setText("Return Book");
        returnBookButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                returnBookButtonMouseClicked(evt);
            }
        });
        returnBookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBookButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout readerDetailPanelLayout = new javax.swing.GroupLayout(readerDetailPanel);
        readerDetailPanel.setLayout(readerDetailPanelLayout);
        readerDetailPanelLayout.setHorizontalGroup(
            readerDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(readerDetailPanelLayout.createSequentialGroup()
                .addGroup(readerDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(readerDetailPanelLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(readerDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(issueBookIdLabel)
                            .addComponent(issueReaderIdLabel)
                            .addGroup(readerDetailPanelLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(readerDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(returnBookIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(returnReaderIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(readerDetailPanelLayout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(returnBookLabel))))
                    .addGroup(readerDetailPanelLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(findIssueButton))
                    .addGroup(readerDetailPanelLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(returnBookButton)))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        readerDetailPanelLayout.setVerticalGroup(
            readerDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(readerDetailPanelLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(returnBookLabel)
                .addGap(79, 79, 79)
                .addComponent(issueBookIdLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(returnBookIdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(issueReaderIdLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(returnReaderIdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(findIssueButton)
                .addGap(18, 18, 18)
                .addComponent(returnBookButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        closeButton.setBackground(new java.awt.Color(72, 159, 181));
        closeButton.setForeground(new java.awt.Color(0, 0, 0));
        closeButton.setText("X");
        closeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeButtonMouseClicked(evt);
            }
        });

        recordsTable.setForeground(new java.awt.Color(0, 0, 0));
        recordsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "issue_id", "book_id", "title", "reader_id", "first_name", "last_name", "issue_date", "due_date", "status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        recordsTable.setToolTipText("");
        recordsTable.setSelectionBackground(new java.awt.Color(22, 105, 122));
        recordsTable.setSelectionForeground(new java.awt.Color(234, 253, 248));
        recordsTable.setSurrendersFocusOnKeystroke(true);
        recordsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                recordsTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(recordsTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(bookDetailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(readerDetailPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 445, Short.MAX_VALUE)
                        .addComponent(closeButton)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bookDetailsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(readerDetailPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(closeButton)
                .addGap(59, 59, 59)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        
    
    public void setRecordDetailsToTable(){
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/biblioteca", "root", "");
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT id_imprumut 'Record ID', id_carte 'Book ID', titlu 'Title', id_cititor 'Reader ID', prenume 'First Name', nume 'Last Name', "
                    + "data_imprumut 'Issue Date', data_expirare 'Due Date', status 'Status' FROM imprumuturi WHERE status = 'Pending'");
            recordsTable.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            e.getStackTrace();
        }
    }
    
    private void backHomeMouseClicked(java.awt.event.MouseEvent evt) {                                      
        // TODO add your handling code here:
        HomePage home = new HomePage();
        home.setVisible(true);
        dispose();
    }                                     

    private void findIssueButtonMouseClicked(java.awt.event.MouseEvent evt) {                                             
        boolean success = false;
        int bookId = Integer.parseInt(returnBookIdField.getText());
        int readerId = Integer.parseInt(returnReaderIdField.getText());
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/biblioteca", "root", "");
            PreparedStatement pst = con.prepareStatement("SELECT * FROM imprumuturi WHERE id_carte = ? AND id_cititor = ? AND status = ?");
            pst.setInt(1, bookId);
            pst.setInt(2, readerId);
            pst.setString(3, "Pending");
            ResultSet rs = pst.executeQuery();
            if(rs.next()){
                success = true;
                issueIdEmptyLabel.setText(rs.getString("id_imprumut"));
                bookTitleEmptyLabel.setText(rs.getString("titlu"));
                firstNameEmptyLabel.setText(rs.getString("prenume"));                
                lastNameEmptyLabel.setText(rs.getString("nume"));
                issueDateEmptyLabel.setText(rs.getString("data_imprumut"));                
                dueDateEmptyLabel.setText(rs.getString("data_expirare"));
                issueErrorLabel.setText("");
            }
            else{
                success = false;
                issueIdEmptyLabel.setText("");
                bookTitleEmptyLabel.setText("");
                firstNameEmptyLabel.setText("");                
                lastNameEmptyLabel.setText("");
                issueDateEmptyLabel.setText("");                
                dueDateEmptyLabel.setText("");
                issueErrorLabel.setText("No record found");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }                                            

    private void findIssueButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
    }                                               

    private void returnReaderIdFieldFocusLost(java.awt.event.FocusEvent evt) {                                              
        
    }                                             

    private void returnReaderIdFieldActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        // TODO add your handling code here:
    }                                                   

    private void returnBookIdFieldFocusLost(java.awt.event.FocusEvent evt) {                                            
        
    }                                           

    private void closeButtonMouseClicked(java.awt.event.MouseEvent evt) {                                         
        System.exit(0);
    }                                        
    
    public void updateBookCount(){
        int bookId = Integer.parseInt(returnBookIdField.getText());
        try{
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/biblioteca", "root", "");
            PreparedStatement pst = con.prepareStatement("UPDATE carti SET cantitate = cantitate + 1 WHERE id_carte = ?"); 
            pst.setInt(1, bookId);
            int rowCount = pst.executeUpdate();
            if(rowCount > 0){
                JOptionPane.showMessageDialog(this, "Book count updated succesfully!");
            }
            else{
                JOptionPane.showMessageDialog(this, "Error: Book count was not updated!");
            }
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }
    
    private void returnBookButtonMouseClicked(java.awt.event.MouseEvent evt) {                                              
        boolean isReturned = false;
        int bookId = Integer.parseInt(returnBookIdField.getText());
        int readerId = Integer.parseInt(returnReaderIdField.getText());
        try{
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/biblioteca", "root", "");
            PreparedStatement pst = con.prepareStatement("UPDATE imprumuturi SET status = ? WHERE id_carte = ? AND id_cititor = ? AND status = ?");
            pst.setString(1, "Returned");
            pst.setInt(2, bookId);            
            pst.setInt(3, readerId);
            pst.setString(4, "Pending");
            int rowCount = pst.executeUpdate();
            if(rowCount > 0){
                JOptionPane.showMessageDialog(this, "Book returned successfully!");
                updateBookCount();
            }
            else
                JOptionPane.showMessageDialog(this, "Error: Book was not returned!");
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }                                             

    private void returnBookButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
    }                                                

    private void recordsTableMouseClicked(java.awt.event.MouseEvent evt) {                                          
        int rowNumber = recordsTable.getSelectedRow();
        TableModel model = recordsTable.getModel();
        returnBookIdField.setText(model.getValueAt(rowNumber, 1).toString());
        returnReaderIdField.setText(model.getValueAt(rowNumber, 3).toString());
    }                                         

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReturnBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton backHome;
    private javax.swing.JLabel bookDetailsLabel;
    private javax.swing.JPanel bookDetailsPanel;
    private javax.swing.JLabel bookTitleEmptyLabel;
    private javax.swing.JLabel bookTitleLabel;
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel dueDateEmptyLabel;
    private javax.swing.JLabel dueDateLabel;
    private javax.swing.JButton findIssueButton;
    private javax.swing.JLabel firstNameEmptyLabel;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JLabel issueBookIdLabel;
    private javax.swing.JLabel issueDateEmptyLabel;
    private javax.swing.JLabel issueDateLabel;
    private javax.swing.JLabel issueErrorLabel;
    private javax.swing.JLabel issueIdEmptyLabel;
    private javax.swing.JLabel issueIdLabel;
    private javax.swing.JLabel issueReaderIdLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lastNameEmptyLabel;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JPanel readerDetailPanel;
    private javax.swing.JTable recordsTable;
    private javax.swing.JButton returnBookButton;
    private javax.swing.JTextField returnBookIdField;
    private javax.swing.JLabel returnBookLabel;
    private javax.swing.JTextField returnReaderIdField;
    // End of variables declaration                   
}
