/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package library;

import java.awt.BorderLayout;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author Darius
 */
public class Statistics extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Statistics() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        backHome = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        pieChartPanel = new javax.swing.JPanel();
        selectStatistics = new javax.swing.JComboBox<>();
        viewStatisticsButton = new javax.swing.JButton();
        dateOneChooser = new com.toedter.calendar.JDateChooser();
        dateTwoChooser = new com.toedter.calendar.JDateChooser();
        categoryLabel = new javax.swing.JLabel();
        dateOneLabel = new javax.swing.JLabel();
        dateTwoLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(234, 253, 248));

        jPanel2.setBackground(new java.awt.Color(22, 105, 122));

        backHome.setBackground(new java.awt.Color(72, 159, 181));
        backHome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        backHome.setForeground(new java.awt.Color(0, 0, 0));
        backHome.setText("Back Home");
        backHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backHomeMouseClicked(evt);
            }
        });

        closeButton.setBackground(new java.awt.Color(72, 159, 181));
        closeButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        closeButton.setForeground(new java.awt.Color(0, 0, 0));
        closeButton.setText("X");
        closeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeButtonMouseClicked(evt);
            }
        });
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(234, 253, 248));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-combo-chart-24.png"))); // NOI18N
        jLabel1.setText("Statistics");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backHome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(closeButton)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(427, 427, 427)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backHome)
                    .addComponent(closeButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pieChartPanel.setBackground(new java.awt.Color(201, 201, 201));
        pieChartPanel.setMinimumSize(new java.awt.Dimension(0, 0));
        pieChartPanel.setLayout(new java.awt.BorderLayout());

        selectStatistics.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Most issued books", "Most issues by reader", "Most issues by book genre", "Most issues by book publisher" }));

        viewStatisticsButton.setBackground(new java.awt.Color(72, 159, 181));
        viewStatisticsButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        viewStatisticsButton.setForeground(new java.awt.Color(0, 0, 0));
        viewStatisticsButton.setText("View Statistics");
        viewStatisticsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewStatisticsButtonMouseClicked(evt);
            }
        });
        viewStatisticsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewStatisticsButtonActionPerformed(evt);
            }
        });

        categoryLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        categoryLabel.setForeground(new java.awt.Color(0, 0, 0));
        categoryLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-pie-chart-30.png"))); // NOI18N
        categoryLabel.setText("Category");

        dateOneLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        dateOneLabel.setForeground(new java.awt.Color(0, 0, 0));
        dateOneLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-calendar2-30.png"))); // NOI18N
        dateOneLabel.setText("From Date:");

        dateTwoLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        dateTwoLabel.setForeground(new java.awt.Color(0, 0, 0));
        dateTwoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-calendar2-30.png"))); // NOI18N
        dateTwoLabel.setText("To Date:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(categoryLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(dateOneLabel)
                                        .addComponent(dateTwoLabel)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(26, 26, 26)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(dateOneChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(dateTwoChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(selectStatistics, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 160, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(viewStatisticsButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(pieChartPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pieChartPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(categoryLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selectStatistics, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dateOneLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dateOneChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(dateTwoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dateTwoChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(viewStatisticsButton)))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void setPieChart(){
        Date dateOne = dateOneChooser.getDate();        
        Date dateTwo = dateTwoChooser.getDate();
        if(dateOne != null && dateTwo != null){
            java.sql.Date inputdateOne = new java.sql.Date(dateOne.getTime());
            java.sql.Date inputdateTwo = new java.sql.Date(dateTwo.getTime());
            if(selectStatistics.getSelectedItem().equals("Most issued books")){
                try{
                    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/biblioteca", "root", "");
                    PreparedStatement pst = con.prepareStatement("SELECT titlu, COUNT(*) 'value' FROM imprumuturi WHERE (data_imprumut BETWEEN ? AND ?) GROUP BY titlu");
                    pst.setDate(1, inputdateOne);            
                    pst.setDate(2, inputdateTwo);
                    ResultSet rs = pst.executeQuery();
                    DefaultPieDataset dataSet = new DefaultPieDataset();
                    List<String> books = new ArrayList<>();
                    while(rs.next()){
                        dataSet.setValue(rs.getString("titlu"),rs.getInt("value"));   
                        books.add(rs.getString("titlu"));
                    }

                    JFreeChart pieChart = ChartFactory.createPieChart("Most issued books", dataSet);
                    PiePlot piePlot = (PiePlot) pieChart.getPlot();

                    Color[] colorArray = { Color.RED, Color.GREEN, Color.BLUE, Color.YELLOW, Color.ORANGE, Color.MAGENTA, Color.CYAN, Color.PINK};
                    List<Color> colors = Arrays.asList(colorArray);
                    int i = 0;
                    for(String item : books){
                        piePlot.setSectionPaint(item, colors.get(i));
                        i++;
                    }

                    piePlot.setBackgroundPaint(Color.white);

                    ChartPanel chartPanel = new ChartPanel(pieChart);
                    pieChartPanel.removeAll();
                    pieChartPanel.add(chartPanel, BorderLayout.CENTER);
                    pieChartPanel.validate();
                }catch(Exception e){
                    e.printStackTrace();
                }
            }
            else if(selectStatistics.getSelectedItem().equals("Most issues by reader")){
                try{
                    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/biblioteca", "root", "");
                    PreparedStatement pst = con.prepareStatement("SELECT prenume, nume, COUNT(*) 'value' FROM imprumuturi WHERE (data_imprumut BETWEEN ? AND ?) GROUP BY prenume");
                    pst.setDate(1, inputdateOne);            
                    pst.setDate(2, inputdateTwo);
                    ResultSet rs = pst.executeQuery();
                    DefaultPieDataset dataSet = new DefaultPieDataset();
                    List<String> readers = new ArrayList<>();
                    while(rs.next()){
                        String fullName = rs.getString("prenume") + " " + rs.getString("nume");
                        dataSet.setValue(fullName,rs.getInt("value"));   
                        readers.add(fullName);
                    }

                    JFreeChart pieChart = ChartFactory.createPieChart("Most issues by reader", dataSet);
                    PiePlot piePlot = (PiePlot) pieChart.getPlot();

                    Color[] colorArray = { Color.RED, Color.GREEN, Color.BLUE, Color.YELLOW, Color.ORANGE, Color.MAGENTA, Color.CYAN, Color.PINK};
                    List<Color> colors = Arrays.asList(colorArray);
                    int i = 0;
                    for(String item : readers){
                        piePlot.setSectionPaint(item, colors.get(i));
                        i++;
                    }

                    piePlot.setBackgroundPaint(Color.white);

                    ChartPanel chartPanel = new ChartPanel(pieChart);
                    pieChartPanel.removeAll();
                    pieChartPanel.add(chartPanel, BorderLayout.CENTER);
                    pieChartPanel.validate();
                }catch(Exception e){
                    e.printStackTrace();
                }
            }
            else if(selectStatistics.getSelectedItem().equals("Most issues by book genre")){
                try{
                    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/biblioteca", "root", "");
                    PreparedStatement pst = con.prepareStatement("SELECT gen, COUNT(*) 'value' FROM carti NATURAL JOIN imprumuturi WHERE carti.id_carte = imprumuturi.id_carte AND (data_imprumut BETWEEN ? AND ?) GROUP BY gen;");
                    pst.setDate(1, inputdateOne);            
                    pst.setDate(2, inputdateTwo);
                    ResultSet rs = pst.executeQuery();
                    DefaultPieDataset dataSet = new DefaultPieDataset();
                    List<String> genres = new ArrayList<>();
                    while(rs.next()){
                        dataSet.setValue(rs.getString("gen"),rs.getInt("value"));   
                        genres.add(rs.getString("gen"));
                    }

                    JFreeChart pieChart = ChartFactory.createPieChart("Most issues by book genre", dataSet);
                    PiePlot piePlot = (PiePlot) pieChart.getPlot();

                    Color[] colorArray = { Color.RED, Color.GREEN, Color.BLUE, Color.YELLOW, Color.ORANGE, Color.MAGENTA, Color.CYAN, Color.PINK};
                    List<Color> colors = Arrays.asList(colorArray);
                    int i = 0;
                    for(String item : genres){
                        piePlot.setSectionPaint(item, colors.get(i));
                        i++;
                    }

                    piePlot.setBackgroundPaint(Color.white);

                    ChartPanel chartPanel = new ChartPanel(pieChart);
                    pieChartPanel.removeAll();
                    pieChartPanel.add(chartPanel, BorderLayout.CENTER);
                    pieChartPanel.validate();
                }catch(Exception e){
                    e.printStackTrace();
                }
            }
            else if(selectStatistics.getSelectedItem().equals("Most issues by book publisher")){
                try{
                    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/biblioteca", "root", "");
                    PreparedStatement pst = con.prepareStatement("SELECT editura, COUNT(*) 'value' FROM carti NATURAL JOIN imprumuturi WHERE carti.id_carte = imprumuturi.id_carte AND (data_imprumut BETWEEN ? AND ?) GROUP BY editura;");
                    pst.setDate(1, inputdateOne);            
                    pst.setDate(2, inputdateTwo);
                    ResultSet rs = pst.executeQuery();
                    DefaultPieDataset dataSet = new DefaultPieDataset();
                    List<String> publishers = new ArrayList<>();
                    while(rs.next()){
                        dataSet.setValue(rs.getString("editura"),rs.getInt("value"));   
                        publishers.add(rs.getString("editura"));
                    }

                    JFreeChart pieChart = ChartFactory.createPieChart("Most issues by book publisher", dataSet);
                    PiePlot piePlot = (PiePlot) pieChart.getPlot();

                    Color[] colorArray = { Color.RED, Color.GREEN, Color.BLUE, Color.YELLOW, Color.ORANGE, Color.MAGENTA, Color.CYAN, Color.PINK};
                    List<Color> colors = Arrays.asList(colorArray);
                    int i = 0;
                    for(String item : publishers){
                        piePlot.setSectionPaint(item, colors.get(i));
                        i++;
                    }

                    piePlot.setBackgroundPaint(Color.white);

                    ChartPanel chartPanel = new ChartPanel(pieChart);
                    pieChartPanel.removeAll();
                    pieChartPanel.add(chartPanel, BorderLayout.CENTER);
                    pieChartPanel.validate();
                }catch(Exception e){
                    e.printStackTrace();
                }
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "Please select two valid dates!");
        }
    }
    
    private void backHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backHomeMouseClicked
        HomePage home = new HomePage();
        home.setVisible(true);
        dispose();
    }//GEN-LAST:event_backHomeMouseClicked

    private void closeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeButtonMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeButtonMouseClicked

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_closeButtonActionPerformed

    private void viewStatisticsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewStatisticsButtonMouseClicked
        setPieChart();
    }//GEN-LAST:event_viewStatisticsButtonMouseClicked

    private void viewStatisticsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewStatisticsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewStatisticsButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Statistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Statistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Statistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Statistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Statistics().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backHome;
    private javax.swing.JLabel categoryLabel;
    private javax.swing.JButton closeButton;
    private com.toedter.calendar.JDateChooser dateOneChooser;
    private javax.swing.JLabel dateOneLabel;
    private com.toedter.calendar.JDateChooser dateTwoChooser;
    private javax.swing.JLabel dateTwoLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel pieChartPanel;
    private javax.swing.JComboBox<String> selectStatistics;
    private javax.swing.JButton viewStatisticsButton;
    // End of variables declaration//GEN-END:variables
}
